import type { EmailService, EmailMessage } from "@/lib/integrations/types";
import { theme } from "@/lib/theme";

// ───────── Simulated service (demo / no API key) ─────────

class SimulatedEmailService implements EmailService {
  async send(msg: EmailMessage) {
    console.log(
      `📧 [SIMULÉ] Email → ${msg.to} | sujet: "${msg.subject}"` +
        (msg.attachment ? ` | PJ: ${msg.attachment.name}` : "")
    );
    return { id: `sim_${Date.now()}`, simulated: true };
  }
}

// ───────── Real Brevo service ─────────
// SDK shape (v5.x — @getbrevo/brevo@^5.0.4, generated by Fern):
//   import { BrevoClient } from "@getbrevo/brevo"
//   new BrevoClient({ apiKey: "..." })
//   await client.transactionalEmails.sendTransacEmail({ sender, to, subject, htmlContent, attachment })
//   → resolves to SendTransacEmailResponse { messageId?: string }
// NOTE: The old TransactionalEmailsApi / TransactionalEmailsApiApiKeys pattern from v2/v3
//       does NOT exist in this version.

class BrevoEmailService implements EmailService {
  constructor(
    private apiKey: string,
    private fromEmail: string,
    private fromName: string
  ) {}

  async send(msg: EmailMessage) {
    const { BrevoClient } = await import("@getbrevo/brevo");
    const client = new BrevoClient({ apiKey: this.apiKey });
    const res = await client.transactionalEmails.sendTransacEmail({
      sender: { email: this.fromEmail, name: this.fromName },
      to: [{ email: msg.to, name: msg.toName }],
      subject: msg.subject,
      htmlContent: msg.html,
      attachment: msg.attachment
        ? [{ name: msg.attachment.name, content: msg.attachment.contentBase64 }]
        : undefined,
    });
    const id = res?.messageId ?? `brevo_${Date.now()}`;
    return { id, simulated: false };
  }
}

// ───────── Selector ─────────

export function getEmailService(opts: {
  fromEmail: string;
  fromName: string;
}): EmailService {
  const key = process.env.BREVO_API_KEY?.trim();
  const demo = process.env.DEMO_MODE === "true";
  if (!key || demo) return new SimulatedEmailService();
  return new BrevoEmailService(key, opts.fromEmail, opts.fromName);
}

// ───────── Template helpers ─────────
// Branded, email-safe layout: table-based, inline styles, theme colours.
// Colours come from lib/theme.ts so emails follow a re-skin.

const C = theme.colors;
const SERIF = "Georgia,'Times New Roman',serif";
const SANS = "Arial,Helvetica,sans-serif";
const SUBTLE = "#8a7f73";

function emailShell(opts: {
  businessName: string;
  badge: string;
  accent: string;
  heading: string;
  body: string;
}): string {
  return `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:${C.background};">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${C.background};padding:24px 12px;">
    <tr><td align="center">
      <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;background:#ffffff;border:1px solid ${C.muted};border-radius:16px;overflow:hidden;">
        <tr><td style="background:${opts.accent};padding:22px 28px;">
          <div style="font:600 11px/1 ${SANS};letter-spacing:.18em;text-transform:uppercase;color:rgba(255,255,255,.82);">${opts.badge}</div>
          <div style="font:600 20px/1.2 ${SERIF};color:#ffffff;margin-top:6px;">${opts.businessName}</div>
        </td></tr>
        <tr><td style="padding:28px;">
          <h1 style="font:600 22px/1.3 ${SERIF};color:${C.foreground};margin:0 0 14px;">${opts.heading}</h1>
          ${opts.body}
        </td></tr>
        <tr><td style="padding:16px 28px;border-top:1px solid ${C.muted};font:400 12px/1.5 ${SANS};color:${SUBTLE};">
          ${opts.businessName} — cet email vous a été envoyé suite à votre réservation.
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

function para(t: string): string {
  return `<p style="font:400 15px/1.6 ${SANS};color:${C.foreground};margin:0 0 12px;">${t}</p>`;
}

function detailsBox(rows: [string, string][]): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${C.background};border-radius:12px;margin:4px 0 16px;">
    <tr><td style="padding:14px 16px;">
      ${rows
        .map(
          ([k, v]) =>
            `<div style="font:400 14px/1.7 ${SANS};color:${C.foreground};"><span style="color:${SUBTLE};">${k} :</span> <strong>${v}</strong></div>`
        )
        .join("")}
    </td></tr>
  </table>`;
}

export function confirmationEmailHtml(p: {
  businessName: string;
  resourceName: string;
  range: string;
  total: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Réservation confirmée",
    accent: C.secondary,
    heading: "C'est confirmé ✅",
    body:
      para(`Bonne nouvelle — votre réservation de <strong>${p.resourceName}</strong> est confirmée.`) +
      detailsBox([
        ["Espace", p.resourceName],
        ["Créneau", p.range],
        ["Montant", p.total],
      ]) +
      para("Votre contrat est joint à cet email. À très bientôt !"),
  });
}

export function requestReceivedEmailHtml(p: {
  businessName: string;
  resourceName: string;
  range: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Demande reçue",
    accent: C.primary,
    heading: "Demande bien reçue ✨",
    body:
      para(`Merci ! Nous avons bien reçu votre demande pour <strong>${p.resourceName}</strong>.`) +
      detailsBox([
        ["Espace", p.resourceName],
        ["Créneau", p.range],
      ]) +
      para("Vous recevrez un email de confirmation dès que le gérant l'aura validée."),
  });
}

export function rejectionEmailHtml(p: {
  businessName: string;
  resourceName: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Mise à jour",
    accent: C.foreground,
    heading: "Demande non retenue",
    body:
      para(`Nous sommes désolés : nous ne pouvons pas donner suite à votre demande pour <strong>${p.resourceName}</strong>.`) +
      para("N'hésitez pas à nous solliciter pour une autre date ou un autre espace."),
  });
}

export function adminNotificationEmailHtml(p: {
  resourceName: string;
  customerName: string;
  range: string;
}): string {
  return emailShell({
    businessName: "Administration",
    badge: "Nouvelle demande",
    accent: C.primary,
    heading: "Nouvelle demande de réservation",
    body:
      para(`<strong>${p.customerName}</strong> souhaite réserver un espace.`) +
      detailsBox([
        ["Espace", p.resourceName],
        ["Client", p.customerName],
        ["Créneau", p.range],
      ]) +
      para("Connectez-vous au dashboard pour valider ou refuser la demande."),
  });
}

/* ─────────── CD soi-même — emails de rendez-vous ─────────── */

export function bookingReceivedClientHtml(p: {
  businessName: string;
  clientName: string;
  prestation: string;
  dateLabel: string;
  intro?: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Demande reçue",
    accent: C.primary,
    heading: `Merci ${p.clientName} 🌸`,
    body:
      para(p.intro || "Ta demande de rendez-vous a bien été reçue.") +
      detailsBox([
        ["Prestation", p.prestation],
        ["Créneau souhaité", p.dateLabel],
      ]) +
      para("Charline te recontacte très vite pour confirmer. À très bientôt 🌿"),
  });
}

export function bookingNotifyPraticienneHtml(p: {
  clientName: string;
  clientEmail: string;
  prestation: string;
  dateLabel: string;
}): string {
  return emailShell({
    businessName: "CD soi-même",
    badge: "Nouvelle demande",
    accent: C.secondary,
    heading: "Nouvelle demande de rendez-vous",
    body:
      para(`<strong>${p.clientName}</strong> (${p.clientEmail}) souhaite un rendez-vous.`) +
      detailsBox([
        ["Prestation", p.prestation],
        ["Créneau souhaité", p.dateLabel],
      ]) +
      para("Connecte-toi à ton espace pour valider ou refuser cette demande."),
  });
}

export function bookingConfirmedClientHtml(p: {
  businessName: string;
  clientName: string;
  prestation: string;
  dateLabel: string;
  intro?: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Rendez-vous confirmé",
    accent: C.secondary,
    heading: "C'est confirmé ✨",
    body:
      para(p.intro || `${p.clientName}, ton rendez-vous est confirmé.`) +
      detailsBox([
        ["Prestation", p.prestation],
        ["Le", p.dateLabel],
      ]) +
      para("Prends soin de toi d'ici là. À très vite 🌿"),
  });
}

export function resetPasswordEmailHtml(p: {
  businessName: string;
  url: string;
  name?: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Accès à ton espace",
    accent: C.primary,
    heading: p.name ? `Bonjour ${p.name}` : "Ton mot de passe",
    body:
      para("Voici ton lien sécurisé pour définir (ou réinitialiser) ton mot de passe et accéder à ton espace.") +
      `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:6px 0 16px;"><tr><td style="border-radius:999px;background:${C.primary};"><a href="${p.url}" style="display:inline-block;padding:13px 26px;font:600 15px/1 ${SANS};color:#ffffff;text-decoration:none;border-radius:999px;">Définir mon mot de passe</a></td></tr></table>` +
      para(`<span style="color:${SUBTLE};font-size:13px;">Ce lien est valable 1 heure. Si tu n'es pas à l'origine de cette demande, tu peux ignorer cet email.</span>`),
  });
}

export function questionnaireInviteHtml(p: {
  businessName: string;
  url: string;
  name?: string;
  intro?: string;
}): string {
  return emailShell({
    businessName: p.businessName,
    badge: "Questionnaire",
    accent: C.primary,
    heading: p.name ? `Bonjour ${p.name} 🌸` : "Ton questionnaire",
    body:
      para(p.intro || "Avant notre rendez-vous, peux-tu prendre un moment pour remplir ce court questionnaire ? Il m'aide à préparer au mieux ton accompagnement.") +
      `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:6px 0 16px;"><tr><td style="border-radius:999px;background:${C.primary};"><a href="${p.url}" style="display:inline-block;padding:13px 26px;font:600 15px/1 ${SANS};color:#ffffff;text-decoration:none;border-radius:999px;">Remplir le questionnaire</a></td></tr></table>` +
      para(`<span style="color:${SUBTLE};font-size:13px;">Ce lien t'est personnel et reste valable 14 jours.</span>`),
  });
}
